version: "3.7"
services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: kasjee
      POSTGRES_USER: postgres
      POSTGRES_DB: graphQL
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  server:
    container_name: server
    build:
      context: ./server
    depends_on:
      - db
      - redis
    ports: 
      - "4000:4000"
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - POSTGRES_PASSWORD=kasjee
      - POSTGRES_USER=postgres
      - POSTGRES_DB=graphQL
      - CORS_URL=web
  web:
    container_name: web
    build:
      context: ./web
    depends_on:
      - server
    ports:
      - "3000:3000"
volumes:
  pg_data: null


